name 'jboss7'
maintainer 'Andrew DuFour'
maintainer_email 'andy.k.dufour@gmail.com'
license 'All rights reserved'
description 'Installs/Configures jboss7'
long_description 'Installs/Configures jboss7'
version '0.11.2'

depends 'apt'
depends 'java'
depends 'ark'
